import { Roboto } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";
import AllPopularCourses from "@/components/AllPopularCourses";

const robotoFont = Roboto({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${robotoFont.className}  h-full antialiased`}
    >
      <body className="">
        <Navber/>
        
        {children}
        <Footer/>
        </body>
    </html>
  );
}
